In [48]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [5]:
%matplotlib inline
plt.xlabel('area (sqr ft)')
plt.ylabel('price (us$)')
plt.scatter(df.area,df.price,color='red',marker='+')

In [6]:
# Create linear regression object
reg = linear_model.LinearRegression()
reg.fit(df[['area']],df.price)

LinearRegression()

In [11]:
reg.predict([[3200]])

array([615136.98630137])

In [12]:
reg.coef_

array([135.78767123])

In [13]:
reg.intercept_

180616.43835616432

In [21]:
%matplotlib inline
plt.xlabel('area (sqr ft)',fontsize=20)
plt.ylabel('price (us$)',fontsize=20)
plt.scatter(df.area,df.price,color='red',marker='+')
plt.plot(df.area,reg.predict(df[['area']]),color='red',marker='+')



In [15]:
area_df = pd.read_csv("areas.csv")
area_df.head(3)

area
0  1000
1  1500
2  2300

In [16]:
p = reg.predict(area_df)
p

array([ 316404.10958904,  384297.94520548,  492928.08219178,
        661304.79452055,  740061.64383562,  799808.21917808,
        926090.75342466,  650441.78082192,  825607.87671233,
        492928.08219178, 1402705.47945205, 1348390.4109589 ,
       1144708.90410959])

In [17]:
area_df['prices']=p
area_df

area        prices
0   1000  3.164041e+05
1   1500  3.842979e+05
2   2300  4.929281e+05
3   3540  6.613048e+05
4   4120  7.400616e+05
5   4560  7.998082e+05
6   5490  9.260908e+05
7   3460  6.504418e+05
8   4750  8.256079e+05
9   2300  4.929281e+05
10  9000  1.402705e+06
11  8600  1.348390e+06
12  7100  1.144709e+06

In [18]:
#exercise 
area_df.to_csv("prediction.csv")

In [30]:
#exercise 

capital_income_df = pd.read_csv("canada_per_capita_income.csv")
capital_income_df .head(3)

year  per capita income (US$)
0  1970              3399.299037
1  1971              3768.297935
2  1972              4251.175484

In [42]:
capital_income_df.rename(columns = {'per capita income (US$)':'per_capita_income_US_doller'}, inplace = True)

In [43]:
capital_income_df .head(3)

year  per_capita_income_US_doller
0  1970                  3399.299037
1  1971                  3768.297935
2  1972                  4251.175484

In [44]:
%matplotlib inline
plt.xlabel('Year')
plt.ylabel('Per Capital Income (us$)')
plt.scatter(capital_income_df.year,capital_income_df.per_capita_income_US_doller,color='red',marker='+')

In [45]:
reg = linear_model.LinearRegression()
reg.fit(capital_income_df[['year']],capital_income_df.per_capita_income_US_doller)



LinearRegression()

In [46]:
reg.predict([[2020]])

array([41288.69409442])

In [47]:
plt.xlabel('Year',fontsize=20)
plt.ylabel('Per Capital Income (us$) ',fontsize=20)
plt.scatter(capital_income_df.year,capital_income_df.per_capita_income_US_doller,color='red',marker='+')
plt.plot(capital_income_df.year,reg.predict(capital_income_df[['year']]),color='red',marker='+')

In [55]:
sns.scatterplot(x="year",y="per_capita_income_US_doller",hue="per_capita_income_US_doller",data=capital_income_df)

<AxesSubplot:xlabel='year', ylabel='per_capita_income_US_doller'>