In [11]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [12]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [13]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [14]:
model.coef_

array([135.78767123])

In [15]:
model.intercept_

180616.43835616432

In [16]:
model.predict([[5000]])

array([859554.79452055])

In [17]:
import pickle

In [18]:
#open file

with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [19]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [20]:
mp.coef_

array([135.78767123])

In [21]:
mp.intercept_

180616.43835616432

In [22]:
mp.predict([[5000]])

array([859554.79452055])

In [23]:
import joblib

In [24]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [25]:
mj = joblib.load('model_joblib')

In [26]:
mj.coef_

array([135.78767123])

In [27]:
mj.intercept_

180616.43835616432

In [28]:
mj.predict([[5000]])

array([859554.79452055])