In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [4]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9611111111111111

In [5]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.4185185185185185

In [6]:
rf = RandomForestClassifier(n_estimators=30)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9722222222222222

In [7]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [9]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [10]:
 get_score(SVC(),X_train, X_test, y_train, y_test)

0.987037037037037

In [11]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index,test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index],digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_logistic.append( get_score(LogisticRegression(),X_train, X_test, y_train, y_test))
    scores_svm.append( get_score(SVC(gamma='auto'),X_train, X_test, y_train, y_test))
    scores_rf.append( get_score(RandomForestClassifier(),X_train, X_test, y_train, y_test))
  
    

C:\Users\Madusha\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Madusha\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_i

In [12]:
scores_logistic

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [13]:
scores_svm 

[0.41068447412353926, 0.41569282136894825, 0.4273789649415693]

In [14]:
scores_rf

[0.9348914858096828, 0.9482470784641068, 0.9198664440734557]

In [15]:
from sklearn.model_selection import cross_val_score

In [16]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [17]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [18]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.93489149, 0.95158598, 0.91819699])

In [19]:
cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target,cv=3)

array([0.82971619, 0.86644407, 0.87813022])

In [20]:
cross_val_score(RandomForestClassifier(n_estimators=15),digits.data, digits.target,cv=3)

array([0.91318865, 0.92153589, 0.9148581 ])

In [21]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data, digits.target,cv=3)

array([0.92654424, 0.95993322, 0.92821369])

In [22]:
cross_val_score(RandomForestClassifier(n_estimators=60),digits.data, digits.target,cv=3)

array([0.94156928, 0.94991653, 0.93155259])

In [23]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=50),digits.data, digits.target, cv=10)
np.average(scores1)

0.9476846679081316

In [24]:
scores2 = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)
np.average(scores2)

0.9193099610461881

In [25]:
scores3 = cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)
np.average(scores3)

0.4346132442960489